In [3]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [4]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [5]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [7]:
df['rooms_per_household'] = df['total_rooms'] / df['households']
df['bedrooms_per_room'] = df['total_bedrooms'] / df['total_rooms']
df['population_per_household'] = df['population'] / df['households']

In [8]:
from sklearn.model_selection import train_test_split

X = df.drop('median_house_value', axis=1)
y = df['median_house_value']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
pd.DataFrame(X_train)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,rooms_per_household,bedrooms_per_room,population_per_household
4679,-118.07,33.81,22.0,2711.0,352.0,1305.0,368.0,8.5407,7.366848,0.129841,3.546196
2512,-117.63,33.50,12.0,3619.0,536.0,1506.0,492.0,7.2013,7.355691,0.148107,3.060976
993,-117.09,32.57,17.0,444.0,83.0,357.0,87.0,5.1478,5.103448,0.186937,4.103448
1327,-117.16,32.81,34.0,2275.0,375.0,1021.0,379.0,3.6371,6.002639,0.164835,2.693931
4630,-118.07,34.17,36.0,2415.0,394.0,1215.0,413.0,5.5418,5.847458,0.163147,2.941889
...,...,...,...,...,...,...,...,...,...,...,...
11284,-121.13,37.74,21.0,2376.0,475.0,1175.0,441.0,3.6016,5.387755,0.199916,2.664399
11964,-121.38,38.62,41.0,774.0,144.0,356.0,150.0,3.5625,5.160000,0.186047,2.373333
5390,-118.15,33.91,38.0,901.0,205.0,760.0,208.0,2.9643,4.331731,0.227525,3.653846
860,-117.07,32.56,9.0,3648.0,895.0,3293.0,840.0,3.0992,4.342857,0.245340,3.920238
15795,-122.41,37.75,52.0,2452.0,623.0,1932.0,549.0,2.3903,4.466302,0.254078,3.519126

In [10]:
pd.DataFrame(y_test)

       median_house_value
10941            142700.0
5250             500001.0
10292             61800.0
2266             162800.0
6398              90600.0
...                   ...
4706             211400.0
8404             500001.0
11114            162500.0
7877             360700.0
6188             137500.0

[3400 rows x 1 columns]

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
pd.DataFrame(X_train_scaled).mean()

0    -8.338428e-16
1     2.162976e-16
2     1.253899e-17
3     5.224579e-17
4    -6.217249e-17
5     6.739707e-17
6     1.044916e-18
7    -5.825406e-17
8    -1.222551e-16
9    -2.716781e-17
10   -3.186993e-17
dtype: float64

In [13]:
pd.DataFrame(X_train_scaled).std()

0     1.000037
1     1.000037
2     1.000037
3     1.000037
4     1.000037
5     1.000037
6     1.000037
7     1.000037
8     1.000037
9     1.000037
10    1.000037
dtype: float64

In [14]:
from sklearn.linear_model import Ridge

model = Ridge(alpha=1.0)
model.fit(X_train_scaled, y_train)

Ridge()

INSTEAD OF LR WE ARE USING RIDGE REGRESSION

In [15]:
y_pred=model.predict(X_test_scaled)

In [17]:
pd.DataFrame(y_pred)

                  0
0     143847.292113
1     400180.868511
2      80060.951250
3     147587.241172
4     148970.218105
...             ...
3395  177961.244015
3396  386794.270956
3397   56531.607087
3398  284027.540389
3399  147580.658939

[3400 rows x 1 columns]

In [18]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

mae, rmse, r2

(49204.971004423984, np.float64(67472.33755486958), 0.6696010963868102)